apiVersion: v1
kind: Service
metadata:
  name: cdn-service
  labels:
    app: cdn
spec:
  ports:
  - port: 443
    targetPort: 8443
    name: https
  - port: 1935
    protocol: TCP
    name: tcp
  externalIPs:
    - 134.134.172.74
  selector:
    app: cdn
