
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-0
  labels:
    app: live-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-0
  template:
    metadata:
      labels:
        app: live-0
    spec:
      enableServiceLinks: false
      containers:
        - name: live-0
          image: jfsxw001.jf.intel.com:10443/ovc_software_transcode_service:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 8
              memory: 6000Mi
            requests:
              cpu: 4
              memory: 3000Mi
          env:
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /var/www/video
              name: video-cache
            - mountPath: /var/www/archive
              name: video-archive
              readOnly: true
      volumes:
          - name: video-cache
            persistentVolumeClaim:
               claimName: video-cache
          - name: video-archive
            persistentVolumeClaim:
               claimName: video-archive
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: "xeone3-zone"
                    operator: NotIn
                    values:
                       - "xeone3"
