apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cdn-service
  name: cdn-service
spec:
  selector:
    matchLabels:
      app: cdn-service
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cdn-service
    spec:
      containers:
      - args:
        - bash
        - -c
        - /home/main.py&/usr/local/sbin/nginx
        image: {{ $.Values.registryPrefix }}ovc_cdn_service:latest
        imagePullPolicy: IfNotPresent
        name: cdn-service
        ports:
        - containerPort: 8443
        - containerPort: 1935
        volumeMounts:
          - mountPath: /var/run/secrets
            name: secrets
            readOnly: true
          - mountPath: /var/www/archive
            name: archive
            readOnly: true
          - mountPath: /var/www/video
            name: cache
      volumes:
        - name: secrets
          secret:
            secretName: self-signed-certificate
        - name: archive
          persistentVolumeClaim:
            claimName: video-archive
        - name: cache
          persistentVolumeClaim:
            claimName: video-cache
      restartPolicy: Always
