apiVersion: v1
kind: Service
metadata:
  labels:
    app: cdn-service
  name: cdn-service
spec:
  ports:
{{- if eq "cdn" $.Values.scenario }}
  - name: "443"
    port: 443
    targetPort: 8443
{{- end }}
  - name: "1935"
    port: 1935
    targetPort: 1935
  externalIPs:
    - "{{ .Values.cdn.hostIP }}"
  selector:
    app: cdn-service
