
{{- range $i,$v1 := .Values.liveTranscode.streams }}
{{- if lt (int $i) (int $.Values.liveTranscode.replicas) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: live-service-{{ $i }}
  name: live-service-{{ $i }}
spec:
  selector:
    matchLabels:
      app: live-service-{{ $i }}
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: live-service-{{ $i }}
    spec:
      containers:
      - image: {{ $.Values.registryPrefix }}ovc_software_transcode_service:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/local/bin/ffmpeg","-re","-stream_loop","-1",
            "-i","{{ .name }}",
{{- range $k,$v2 := .transcode }}
            "-vf","scale={{ .scale }}",
            "-c:v","{{ .encoderType }}",
            "-b:v","{{ .bitrate }}",
            "-r","{{ .framerate }}",
            "-g","{{ .gop }}",
            "-bf","{{ .maxbframes }}",
            "-refs","{{ .refsNum }}",
            "-preset","{{ .preset }}",
            "-forced-idr","1",
{{- if eq ( hasPrefix "libsvt" .encoderType ) true }}
            "-thread_count","96",
{{- end }}
            "-an",
            "-f","flv","rtmp://cdn-service/{{ .protocol }}/media_{{ $i }}_{{ $k }}",
{{- end }}
            "-abr_pipeline"]
        lifecycle:
          preStop:
            exec:
              command:
              - rm
              - -rf
{{- range $k,$v2 := .transcode }}
              - ' /var/www/video/{{ .protocol }}/media_{{ $i }}_{{ $k }}'
{{- end }}
        name: live-service-{{ $i }}
        env:
          - name: NO_PROXY
            value: "cdn-service"
          - name: no_proxy
            value: "cdn-service"
        volumeMounts:
          - mountPath: /var/www/archive
            name: archive
            readOnly: true
      volumes:
        - name: archive
          persistentVolumeClaim:
            claimName: video-archive
      restartPolicy: Always

---
{{- end }}
{{- end }}
