apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: live-service
  name: live-service
spec:
  selector:
    matchLabels:
      app: live-service
  replicas: {{ .Values.liveTranscode.replicas }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: live-service
    spec:
      containers:
      - image: ovc_software_transcode_service:latest
        imagePullPolicy: IfNotPresent
        name: live-service
      restartPolicy: Always
