apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: live-service
  name: live-service
spec:
  selector:
    matchLabels:
      app: live-service
  replicas: {{ .Values.liveTranscode.replicas }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: live-service
    spec:
      containers:
      - image: ovc_software_transcode_service:latest
        command: ["/bin/bash","-c","ffmpeg -re -stream_loop -1 -i /var/www/archive/bbb_sunflower_1080p_30fps_normal.mp4 -vf scale=2560:1440 -c:v libsvt_hevc -b:v 15M -forced-idr 1 -f flv rtmp://cdn-service/hls/big_buck_bunny_2560x1440 -vf scale=1920:1080 -c:v libsvt_hevc -b:v 10M -forced-idr 1 -f flv rtmp://cdn-service/hls/big_buck_bunny_1920x1080 -vf scale=1280:720 -c:v libx264 -b:v 8M -f flv rtmp://cdn-service/hls/big_buck_bunny_1280x720 -vf scale=854:480 -c:v libx264 -b:v 6M -f flv rtmp://cdn-service/hls/big_buck_bunny_854x480 -abr_pipeline"]
        imagePullPolicy: IfNotPresent
        name: live-service
        volumeMounts:
          - mountPath: /var/www/archive
            name: archive
            readOnly: true
      volumes:
        - name: archive
          persistentVolumeClaim:
            claimName: video-archive
      restartPolicy: Always
