apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-service
  name: redis-service
spec:
  selector:
    matchLabels:
      app: redis-service
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-service
    spec:
      containers:
      - args:
        - redis-server
        image: redis:latest
        imagePullPolicy: IfNotPresent
        name: redis-service
        ports:
        - containerPort: 6379
        securityContext:
          runAsUser: 999
      restartPolicy: Always
