
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-archive
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: video-archive
  resources:
    requests:
      storage: "{{ .Values.volume.video.archive.size }}"

