
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-hls
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: video-hls
  resources:
    requests:
      storage: "{{ .Values.volume.video.hls.size }}"

