apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vod-service
  name: vod-service
spec:
  selector:
    matchLabels:
      app: vod-service
  replicas: {{ .Values.vodTranscode.replicas }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vod-service
    spec:
      containers:
      - args:
        - bash
        - -c
        - /home/main.py
        image: {{ $.Values.registryPrefix }}ovc_software_transcode_service:latest
        imagePullPolicy: IfNotPresent
        name: vod-service
        volumeMounts:
          - mountPath: /var/www/archive
            name: archive
            readOnly: true
          - mountPath: /var/www/dash
            name: dash
          - mountPath: /var/www/hls
            name: hls
      volumes:
        - name: archive
          persistentVolumeClaim:
            claimName: video-archive
        - name: dash
          persistentVolumeClaim:
            claimName: video-dash
        - name: hls
          persistentVolumeClaim:
            claimName: video-hls
      restartPolicy: Always
