
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vod-service
  name: vod-service
spec:
  selector:
    matchLabels:
      app: vod-service
  replicas: {{ .Values.vodTranscode.replicas }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vod-service
    spec:
      containers:
      - args:
        - bash
        - -c
        - /home/main.py
        image: {{ $.Values.registryPrefix }}tc_transcode_{{ lower $.Values.platform }}:latest
        imagePullPolicy: IfNotPresent
        name: vod-service
        volumeMounts:
          - mountPath: /var/www/archive
            name: archive
            readOnly: true
          - mountPath: /var/www/video
            name: cache
      volumes:
        - name: archive
          persistentVolumeClaim:
            claimName: video-archive
        - name: cache
          persistentVolumeClaim:
            claimName: video-cache
      restartPolicy: Always
