apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
  name: node-exporter
  namespace: pgmon
spec:
  type: NodePort
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
    nodePort: 30003
  selector:
    k8s-app: node-exporter
