{
 "title": "k8s-☸-pgmon/cAdvisor-Brief",
 "tags": [
  "容器",
  "容器资源指标"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "容器正在使用的核心数",
   "type": "graph",
   "description": "container_cpu_usage_seconds_total -总和。在Kubernetes 1.9之前，会报告所有节点中的每个CPU。这在1.1.0中发生了变化",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[$Interval])) by (container_name,pod_name)",
     "legendFormat": "pod : {{ pod_name }} {{ container_name }}"
    }
   ]
  },
  {
   "title": "容器CPU受限时间",
   "type": "graph",
   "description": "与CPU极限计算饱和,随着定义了CPU使用率的上限。当容器超过其CPU限制时，Linux运行时将“限制”容器并记录它在系列中受限制的时间container_cpu_cfs_throttled_seconds_total。这是一个计数器再次跟踪每个容器，所以采取rate",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_cfs_throttled_seconds_total{image!=\"\"}[$Interval]))\r\nby (container_name,pod_name)",
     "legendFormat": "pod : {{ pod_name }} {{ container_name }}"
    }
   ]
  },
  {
   "title": "内存利用率",
   "type": "graph",
   "description": "我们需要排除名称中包含“POD”的容器。这是此容器的父cgroup，将跟踪窗格中所有容器的统计信息。\n\n你可能认为可以轻松跟踪内存利用率container_memory_usage_bytes，但是，此度量标准还包括可以在内存压力下逐出的缓存（思考文件系统缓存）项。更好的衡量标准是container_memory_working_set_bytes因为这是OOM正在关注的内容。",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate\n(container_memory_working_set_bytes{name!~\"POD\",container_name!=\"POD\",image!=\"\"}[$Interval]))\nby (name,container_name,pod_name)",
     "legendFormat": "{{ pod_name }} {{ container_name }}"
    }
   ]
  },
  {
   "title": "内存饱和度",
   "type": "graph",
   "description": "在这里，我们必须加入两个系列，一个来自cAdvisor，另一个来自kube-state-metrics。不幸的是，容器名称标签没有对齐，但PromQL对此有帮助label_join",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum\r\n(container_memory_working_set_bytes{image!=\"\",container_name!=\"POD\"}) by (container_name) / \r\nsum\r\n(label_join(kube_pod_container_resource_limits_memory_bytes,\"container_name\", \"\", \"container\")) \r\nby (container_name,pod_name)",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "磁盘I/O利用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total[5m])) by (container_name,device)",
     "legendFormat": "{{ container_name }}  writes"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total[5m])) by (container_name,device)",
     "legendFormat": "{{ container_name }}  reads"
    }
   ]
  },
  {
   "title": "Pod 接受的网络字节数",
   "type": "graph",
   "description": "容器级别的网络利用率，您可以选择以字节为单位测量，也可以选择发送和接收的数据包。这个查询有点不同，因为所有网络会计都发生在Pod级别，而不是容器！",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name}} "
    }
   ]
  },
  {
   "title": "Pod 累计的网络字节数",
   "type": "graph",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\"}[$Interval])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\"}[$Interval])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "接收时丢弃的数据包总数",
   "type": "graph",
   "description": "Cumulative count of packets dropped while receiving",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_packets_dropped_total{image!=\"\"}",
     "legendFormat": "{{ namespace }} {{ pod_name }}"
    }
   ]
  }
 ]
}
{
 "title": "k8s-☸-pgmon/cAdvisor-namespace",
 "description": "namespace cadvisor describe",
 "tags": [
  "namespace ",
  "容器",
  "资源状态"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase,namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "content": "- 参考 https://github.com/kubernetes/kube-state-metrics/tree/master/Documentation"
  },
  {
   "title": "configMap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "configMap",
     "type": "table",
     "gridPos": { "h": 5, "w": 15, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(kube_configmap_info) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "secret 计数",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "secret共计",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "sum(kube_secret_info)" }
     ]
    },
    {
     "title": "describe",
     "type": "table",
     "gridPos": { "h": 6, "w": 19, "x": 5, "y": 4 },
     "targets": [
      {
       "expr": "sum(kube_secret_type) by (namespace,secret,type)"
      }
     ]
    },
    {
     "title": "$namespace secre",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_secret_info{namespace=~\"^$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "全部名称空间",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_namespace_status_phase)"
      }
     ]
    },
    {
     "title": "Active名称空间数",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 5, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_namespace_status_phase{phase=\"Active\"})"
      }
     ]
    },
    {
     "title": "Terminating",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_namespace_status_phase{phase=\"Terminating\"})"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "max(kube_namespace_status_phase{phase=\"Active\"}) by (phase,namespace)"
      },
      {
       "expr": "sum(max(kube_namespace_status_phase{phase=\"Terminating\"}) by (phase,namespace))"
      }
     ]
    }
   ]
  },
  {
   "title": "service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "service status",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "max(kube_service_info) by (service,namespace,cluster_ip)"
      }
     ]
    }
   ]
  },
  {
   "title": "replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "ReplicaSet指标",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "max(kube_replicaset_status_replicas) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_status_fully_labeled_replicas) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_status_ready_replicas) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_status_observed_generation) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_spec_replicas) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_metadata_generation) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_created) by (replicaset,namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 10, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "总内存大小",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "$namespace容器占用比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\",namespace=\"$namespace\"})",
     "legendFormat": "{{ $namespace 占用 }} /个"
    },
    {
     "expr": "count(container_last_seen{image!=\"\"})",
     "legendFormat": "总容器 /个"
    }
   ]
  },
  {
   "title": "$namespace内存占用比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",namespace=\"$namespace\"})/1024/1024",
     "legendFormat": "{{ $namespace }} 使用的内存大小"
    },
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024",
     "legendFormat": "容器共使用内存大小 / KB"
    }
   ]
  },
  {
   "title": "$namespace cpu比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",namespace=\"$namespace\"}[5m]) * 100)",
     "legendFormat": "$namespace 使用的CPU"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)",
     "legendFormat": "容器共使用的CPU"
    }
   ]
  },
  {
   "title": "CPU总核心数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode =\"system\"}) by (node)"
    }
   ]
  },
  {
   "title": "kube_pod_status_phase Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "kube_pod_status_phase have failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "$namespace Num",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\",namespace=\"$namespace\"})",
     "legendFormat": "{{ $namespace }}"
    },
    {}
   ]
  },
  {
   "title": "$namespace Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 14 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",namespace=\"$namespace\"})/1024/1024"
    }
   ]
  },
  {
   "title": "$namespace Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",namespace=\"$namespace\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",namespace=~\"^$namespace\",name=~\"^k8s_.*\"}[$interval])) by (pod_name) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=~\"^$namespace\"}[$interval])) by (container_name, pod_name)",
     "legendFormat": "pod: {{pod_name}} {{ container_name }}"
    }
   ]
  },
  {
   "title": "Pod Network  I/O 5分钟",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",namespace=~\"^$namespace\",name=~\"^k8s_.*\"}[$interval])) by (pod_name)",
     "legendFormat": "->{{pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",namespace=~\"^$namespace\",name=~\"^k8s_.*\"}[$interval])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}
{
 "title": "k8s-☸-pgmon/Docker monitoring  ALL",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "所有容器大盘表" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "pgmon", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100",
     "legendFormat": "{{ container_name}} {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{ container_name}} {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"\"}[5m])",
     "legendFormat": "{{ container_name}} {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\"}[5m])",
     "legendFormat": "{{ container_name}} {{ pod_name }}"
    }
   ]
  }
 ]
}
{
 "title": "k8s-☸-pgmon/Kubernetes API",
 "tags": [ "Kubernetes API" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "content": "- 请求率和延迟\r\n- 控制器工作队列的性能\r\n- Etcd helper 缓存工作队列和缓存性能"
  },
  {
   "title": "请求速率/5m",
   "type": "graph",
   "description": "这通过verb提供的所有kubernetes的5分钟的速率，其中包括所有的动作： WATCH, PUT, POST, PATCH, LIST, GET, DELETE, and CONNECT.",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[5m])) by (resource, subresource, verb)",
     "legendFormat": "{{ resource}} {{ subresource }} {{ verb  }}"
    }
   ]
  },
  {
   "title": "http 5xx错误与请求率的比率",
   "type": "graph",
   "description": "HTTP服务器的错误跟踪为HTTP 5xx错误。使用此查询可以获得错误与请求率的比率",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_request_count{code=~\"^(?:5..)$\"}[5m]) / rate(apiserver_request_count[5m])",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "API响应分布",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(apiserver_request_latencies_bucket{subresource!=\"log\",verb!~\"^(?:CONNECT|WATCHLIST|WATCH|PROXY)$\"}) WITHOUT (instance, resource)) / 1e+06",
     "legendFormat": "{{ job }}{{ scope }} {{ verb }}"
    }
   ]
  },
  {
   "title": "API控制器工作队列的性能",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "APIServiceRegistrationController_adds",
     "legendFormat": "{{ instance }} {{ job }} workqueue 处理的添加总数:"
    },
    {
     "expr": "APIServiceRegistrationController_depth",
     "legendFormat": "{{ instance }} {{ job }}  当前工作深度："
    },
    {
     "expr": "APIServiceRegistrationController_queue_latency",
     "legendFormat": "{{ instance }} {{ job }}  {{ quantile }} 队列延迟分布"
    },
    {
     "expr": "APIServiceRegistrationController_queue_latency_count",
     "legendFormat": "{{ instance }} {{ job }}   队列延迟计数"
    },
    {
     "expr": "APIServiceRegistrationController_queue_latency_sum",
     "legendFormat": "{{ instance }} {{ job }}  队列延迟总和"
    },
    {
     "expr": "APIServiceRegistrationController_retries",
     "legendFormat": "{{ instance }} {{ job }}   工作队列处理的重试总次数"
    },
    {
     "expr": "APIServiceRegistrationController_work_duration",
     "legendFormat": "{{ instance }} {{ job }}  {{ quantile }} 处理所需时长"
    },
    {
     "expr": "APIServiceRegistrationController_work_duration_count",
     "legendFormat": "{{ instance }} {{ job }} 工作时间计数"
    },
    {
     "expr": "APIServiceRegistrationController_work_duration_sum",
     "legendFormat": "{{ instance }} {{ job }}  持续时间总和"
    }
   ]
  },
  {
   "title": "Etcd交互",
   "type": "graph",
   "description": "如果在一段时间内没有请求，则无法计算百分位数。在那种情况下报告NaN。",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "etcd_helper_cache_entry_count", "legendFormat": "{{ instance }} 缓存中的元素数" },
    { "expr": "etcd_helper_cache_hit_count", "legendFormat": "{{ instance }}  缓存命中数" },
    { "expr": "etcd_helper_cache_miss_count", "legendFormat": "{{ instance }}  缓存未命中数" },
    {
     "expr": "etcd_request_cache_add_latencies_summary_count",
     "legendFormat": "{{ instance }}  缓存添加数量"
    },
    {
     "expr": "etcd_request_cache_add_latencies_summary_sum ",
     "legendFormat": "{{ instance }}  将项目放入缓存所花费的总时间"
    },
    {
     "expr": "histogram_quantile(0.9,rate(etcd_request_cache_get_latencies_summary[5m]))"
    },
    {
     "expr": "etcd_request_cache_get_latencies_summary_count",
     "legendFormat": "{{ instance }} 缓存获取次数的计数"
    },
    {
     "expr": "etcd_request_cache_get_latencies_summary_sum",
     "legendFormat": "{{ instance }} 缓存中获取项目所花费的总时间"
    },
    {
     "expr": "sum(rate(etcd_request_cache_add_latencies_summary[5m])) by (instance,quantile)"
    },
    {
     "expr": "rate(etcd_request_cache_add_latencies_summary_sum[5m])  / rate(etcd_request_cache_add_latencies_summary_count[5m])"
    }
   ]
  }
 ]
}
{
 "title": "k8s-☸-pgmon/Node Exporter Server Metrics",
 "description": "Dashboard to view multiple servers",
 "tags": [ "主机" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   { "name": "pgmon", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "$node", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode=\"system\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~'$node'}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~'$node'}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~'$node'}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~'$node'}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~'$node'}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~'$node'}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~'$node'}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~'$node'}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~'$node'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "repeat": "node",
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{instance=~'$node'} - node_memory_MemFree_bytes{instance=~'$node'} - node_memory_Buffers_bytes{instance=~'$node'} - node_memory_Cached_bytes{instance=~'$node'} - node_memory_SwapCached_bytes{instance=~'$node'} - node_memory_Slab_bytes{instance=~'$node'} - node_memory_PageTables_bytes{instance=~'$node'} - node_memory_VmallocUsed_bytes{instance=~'$node'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$node'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$node'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~'$node'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~'$node'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~'$node'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{instance=~'$node'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{instance=~'$node'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped_bytes{instance=~'$node'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~'$node'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive_bytes{instance=~'$node'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Utilization per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[5m])/10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~'$node'}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~'$node'}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "repeat": "node",
   "yaxes": [
    {
     "format": "bytes",
     "label": "Bytes/second read (-) / write (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~'$node'}[5m]) * 512",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~'$node'}[5m]) * 512",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[5m])",
     "legendFormat": "context switches"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "repeat": "node",
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "established"
    }
   ]
  },
  {
   "title": "UDP Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node\"}[5m])",
     "legendFormat": "Udp_NoPorts"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$node\"} - node_nf_conntrack_entries{instance=~\"$node\"}",
     "legendFormat": "free"
    }
   ]
  }
 ]
}
{
 "title": "k8s-☸-pgmon/node-exporter-Brief",
 "tags": [
  "节点利用率和饱和度",
  "主机状态监控"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "磁盘状态",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1-sum(node_filesystem_free_bytes{fstype=~\"ext4|xfs\"}) by (instance,device) / sum(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}) by (instance,device)"
    },
    {
     "expr": "max(node_filesystem_free_bytes) by (fstype)"
    },
    {
     "expr": "max(node_filesystem_avail_bytes {fstype=~\"ext4|xfs\"}) by (device,instance)"
    },
    {
     "expr": "max(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}) by (device)  "
    }
   ]
  },
  {
   "title": "节点CPU利用量/5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\",mode!~\"^(?:guest.*)$\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "节点CPU饱和度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1) by (instance ) / count(node_cpu_seconds_total{mode=\"system\"}) by (instance ) * 100",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "节点内存利用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "网络利用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) by (instance) + sum(rate(node_network_transmit_bytes_total[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "网络饱和度",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total[5m])) by (instance) + sum(rate(node_network_transmit_drop_total[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "k8s-☸-pgmon/node-exporter-describe",
 "description": "根据项目划分主机",
 "tags": [ "主机状态监控" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "version",
    "label": "version",
    "query": "label_values(node_exporter_build_info,version)"
   },
   {
    "name": "node",
    "label": "主机",
    "query": "label_values(node_exporter_build_info{version='$version'},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   }
  ]
 },
 "panels": [
  { "title": "所有节点状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "所有节点数量",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Master节点数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(APIServiceRegistrationController_retries)"
    }
   ]
  },
  {
   "title": "节点CPU利用量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\",mode!~\"^(?:guest.*)$\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "节点内存利用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node节点数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_intr_total{instance!~\"^(?:master.*)\"})"
    }
   ]
  },
  { "title": "当前主机状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "node" },
  {
   "title": "系统运行时间",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU使用率（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "当前1分钟CPU Load占用总CPU的百分比",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (node_load1{instance=\"$node\"}) by (node) / (count(node_cpu_seconds_total{mode=\"system\"}) by (node)) * 100"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} - node_memory_Buffers_bytes{instance=~\"$node\"} - node_memory_Cached_bytes{instance=~\"$node\"}) / (node_memory_MemTotal_bytes{instance=~\"$node\"} )) * 100"
    }
   ]
  },
  {
   "title": "当前打开的文件描述符",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "根分区使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ( max(node_filesystem_avail_bytes{instance=~\"$node\",device=\"/dev/mapper/LBVG-root\",fstype=~\"ext4|xfs\"} * 100) / max(node_filesystem_size_bytes{instance=~\"$node\",device=\"/dev/mapper/LBVG-root\",fstype=~\"ext4|xfs\"}))"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "磁盘总空间",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node_filesystem_size_bytes {instance=~\"$node\",fstype=~\"ext4|xfs\"}) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "各分区可用空间",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "max(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}) by (device)"
    },
    {
     "expr": "1-(max(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (device)  / max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (device))"
    },
    {
     "expr": "max(node_filesystem_free_bytes{instance=~'master-1.k8s.org'}) by (fstype)"
    }
   ]
  },
  {
   "title": "CPU使用率、磁盘每秒的I/O操作耗费时间（%）",
   "type": "graph",
   "description": "node_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1m]))",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_每秒I/O操作%"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - (node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"} + node_memory_MemFree_bytes{instance=~\"$node\"})",
     "legendFormat": "已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "可用"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘读写容量大小",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘IO读写时间",
   "type": "graph",
   "description": "Read time ms 每个磁盘分区读操作花费的秒数\n\nWrite time ms 每个磁盘分区写操作花费的秒数\n\nIO time ms 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted 每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  },
  {
   "title": "TCP 连接情况",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  }
 ]
}
{
 "title": "k8s-☸-pgmon/node-exporter-docker",
 "description": "Docker Monitoring Template",
 "tags": [ "主机上的容器监控" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Node",
    "label": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "当前主机运行的容器",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{kubernetes_io_hostname=~\"$Node$\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "当前主机上的容器使用CPU比例",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"$Node\"}[1m] )) / (count(node_cpu_seconds_total{mode=\"system\",kubernetes_io_hostname=~\"$Node\"})) * 100"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "容器网络 i/o",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (container_name, pod_name)",
     "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (container_name, pod_name)",
     "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "容器文件系统读取速率（单位：字节/秒）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{image!=\"\"}[1m])) without (device)",
     "legendFormat": "{{ pod_name }} {{ container_name }} "
    }
   ]
  },
  {
   "title": "容器文件系统写入速率（单位：字节/秒）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{image!=\"\"}[1m])) without (device)",
     "legendFormat": "{{ pod_name }} {{ container_name }} "
    }
   ]
  }
 ]
}