apiVersion: v1
kind: Service
metadata:
  name: k8s-pgmon-grafana
  namespace: pgmon
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30001
  selector:
    app: grafana
status:
  loadBalancer: {}
