version: '3.1'

services:

    redis-service:
        image: redis:latest
        ports:
            - "6379:6379"
        restart: always
        deploy:
            replicas: 1
        command:
            redis-server

    zookeeper-service:
        image: zookeeper:latest
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: '2181'
            ZOOKEEPER_TICK_TIME: '2000'
            ZOOKEEPER_HEAP_OPTS: '-Xmx2048m -Xms2048m'
            ZOOKEEPER_MAX_CLIENT_CNXNS: '20000'
            ZOOKEEPER_LOG4J_LOGGERS: 'zookeepr=ERROR'
            ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: 'ERROR'
        restart: always
        deploy:
            replicas: 1

    kafka-service:
        image: wurstmeister/kafka:latest
        depends_on:
            - zookeeper-service
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_HOST_NAME: 'kafka-service'
            KAFKA_ADVERTISED_PORT: '9092'
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-service:2181'
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-service:9092'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_DEFAULT_REPLICATION_FACTOR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_NUM_PARTITIONS: 16
            KAFKA_CREATE_TOPICS: 'content_provider_sched:16:1'
            KAFKA_LOG_RETENTION_HOURS: 8
            KAFKA_HEAP_OPTS: '-Xmx1024m -Xms1024m'
            KAFKA_LOG4J_LOGGERS: 'kafka=ERROR,kafka.controller=ERROR,state.change.logger=ERROR,org.apache.kafka=ERROR'
            KAFKA_LOG4J_ROOT_LOGLEVEL: 'ERROR'
        restart: always
        deploy:
            replicas: 1

    cdn-service:
        image: ovc_cdn_service:latest
        ports:
            - "443:8080"
        volumes:
            - ${HTML_VOLUME}:/var/www/html:ro
            - ${VIDEO_ARCHIVE_VOLUME}:/var/www/archive:rw
            - ${VIDEO_DASH_VOLUME}:/var/www/dash:rw
            - ${VIDEO_HLS_VOLUME}:/var/www/hls:rw
            - ${NGINX_LOG_VOLUME}:/var/www/log:rw
        depends_on:
            - kafka-service
        deploy:
            replicas: 1
        secrets:
            - source: self_crt
              target: /var/run/secrets/self.crt
              uid: ${USER_ID}
              gid: ${GROUP_ID}
              mode: 0444
            - source: self_key
              target: /var/run/secrets/self.key
              uid: ${USER_ID}
              gid: ${GROUP_ID}
              mode: 0440

    vod-transcode-service:
        image: ovc_transcode_service:latest
        volumes:
            - ${VIDEO_ARCHIVE_VOLUME}:/var/www/archive:ro
            - ${VIDEO_DASH_VOLUME}:/var/www/dash:rw
            - ${VIDEO_HLS_VOLUME}:/var/www/hls:rw
        deploy:
            replicas: 2
        depends_on:
            - kafka-service
            - zookeeper-service

    live-transcode-service:
        image: ovc_transcode_service:latest
        volumes:
            - ${VIDEO_ARCHIVE_VOLUME}:/var/www/archive:ro
        depends_on:
            - cdn-service
        command: |
              bash -c 'ffmpeg -re -stream_loop -1 -i /var/www/archive/bbb_sunflower_1080p_30fps_normal.mp4 -vf scale=2560:1440 -c:v libsvt_hevc -b:v 15M -forced-idr 1 -f flv rtmp://cdn-service/hls/big_buck_bunny_2560x1440 -vf scale=1920:1080 -c:v libsvt_hevc -b:v 10M -forced-idr 1 -f flv rtmp://cdn-service/hls/big_buck_bunny_1920x1080 -vf scale=1280:720 -c:v libx264 -b:v 8M -f flv rtmp://cdn-service/hls/big_buck_bunny_1280x720 -vf scale=854:480 -c:v libx264 -b:v 6M -f flv rtmp://cdn-service/hls/big_buck_bunny_854x480 -abr_pipeline'

secrets:
    self_key:
        file: ${SECRETS_VOLUME}/self.key
    self_crt:
        file: ${SECRETS_VOLUME}/self.crt
