---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: k8s-pgmon-prometheus
  namespace: pgmon
spec:
  type: NodePort
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30002

  selector:
    app: prometheus
