apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: kube-prometheus
data:
  CDN-Transcode-Sample_rules.yml: |
    groups:
    - name: CDN-Transcode-Sample-nodes
      rules:
      - alert: InstanceDown
        expr: up{job="CDN-Transcode-Sample-nodes"} == 0
        for: 5s
        annotations:
          summary: "Instance down --------- {{ $labels.job }} ----------------"
          description: "has been down for more {{ $value }} than minutes."

      - alert: NodeMemoryUsage
        expr: (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100 > 20
        for: 2m
        annotations:
          summary: "{{$labels.instance}}: High Memory usage detected"
          description: "{{$labels.instance}}: Memory usage is above 20%, current value is: {{$value}}"

      - alert: NodeCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{job="CDN-Transcode-Sample-nodes",mode="idle"}[5m])) * 100) > 80
        for: 2m
        annotations:
          summary: "{{$labels.instance}}: High CPU usage detected"
          description: "{{$labels.instance}}: CPU usage is above 80% (current value is: {{ $value }}"

    - name: CDN-Transcode-Sample-pods
      rules:
      - alert: PodMemoryUsage
        expr: sum(container_memory_rss{image != ""}) by(pod_name, namespace) / sum(container_spec_memory_limit_bytes{image != ""}) by(pod_name, namespace) * 100 != +Inf > 80
        for: 2m
        annotations:
          summary: "{{$labels.pod_name}}:High Memory usage detected"
          description: "{{$labels.pod_name}}: Memory usage is above 80%, current value is: {{$value}}"

      - alert: PodCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{image != ""}[5m])) by (pod_name, namespace) / (sum(container_spec_cpu_quota{image != ""} / 100000) by (pod_name, namespace)) * 100 != +Inf > 80
        for: 2m
        annotations:
          summary: "{{$labels.pod_name}}:High cpu usage detected"
          description: "{{$labels.pod_name}}: cpu usage is above 80%, current value is: {{$value}}"
