version: '3.1'

services:

    redis-service:
        image: redis:latest
        ports:
            - "6379:6379"
        command:
            redis-server
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "2"
                    memory: 1000M
                reservations:
                    cpus: "1"
                    memory: 500M
            placement:
                constraints:
                    - node.hostname == master.machine

    zookeeper-service:
        image: zookeeper:latest
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: '2181'
            ZOOKEEPER_TICK_TIME: '2000'
            ZOOKEEPER_HEAP_OPTS: '-Xmx2048m -Xms2048m'
            ZOOKEEPER_MAX_CLIENT_CNXNS: '20000'
            ZOOKEEPER_LOG4J_LOGGERS: 'zookeepr=ERROR'
            ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: 'ERROR'
        restart: always
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "2"
                    memory: 1000M
                reservations:
                    cpus: "1"
                    memory: 500M
            placement:
                constraints:
                    - node.hostname == master.machine
        labels:
            kompose.service.type: NodePort

    kafka-service:
        image: wurstmeister/kafka:latest
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper-service
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_HOST_NAME: 'kafka-service'
            KAFKA_ADVERTISED_PORT: '9092'
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-service:2181'
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-service:9092'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_DEFAULT_REPLICATION_FACTOR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_NUM_PARTITIONS: 16
            KAFKA_CREATE_TOPICS: 'content_provider_sched:16:1'
            KAFKA_LOG_RETENTION_HOURS: 8
            KAFKA_HEAP_OPTS: '-Xmx1024m -Xms1024m'
            KAFKA_LOG4J_LOGGERS: 'kafka=ERROR,kafka.controller=ERROR,state.change.logger=ERROR,org.apache.kafka=ERROR'
            KAFKA_LOG4J_ROOT_LOGLEVEL: 'ERROR'
        restart: always
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "2"
                    memory: 1000M
                reservations:
                    cpus: "1"
                    memory: 500M
            placement:
                constraints:
                    - node.hostname == master.machine
        labels:
            kompose.service.type: NodePort

    cdn-service:
        image: ovc_cdn_service:latest
        ports:
            - "8080:8080"
            - "1935:1935"
        depends_on:
            - kafka-service
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "3"
                    memory: 3000M
                reservations:
                    cpus: "1.5"
                    memory: 1500M
            placement:
                constraints:
                    - node.hostname == master.machine
        command: ["bash", "-c", "/home/main.py&/usr/sbin/nginx"]
        labels:
            kompose.service.type: NodePort
            kompose.image-pull-policy: IfNotPresent 

    vod-service:
        image: ovc_transcode_service:latest
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "6"
                    memory: 6000M
                reservations:
                    cpus: "3"
                    memory: 3000M
            placement:
                constraints:
                    - node.hostname == master.machine
        depends_on:
            - kafka-service
            - zookeeper-service
        command: ["bash", "-c", "/home/main.py"]
        labels:
            kompose.image-pull-policy: IfNotPresent

    live-service:
        image: ovc_transcode_service:latest
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "6"
                    memory: 6000M
                reservations:
                    cpus: "3"
                    memory: 3000M
            placement:
                constraints:
                    - node.hostname == master.machine
        depends_on:
            - cdn-service
        labels:
            kompose.image-pull-policy: IfNotPresent
