---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: kube-prometheus
  labels:
    k8s-app: node-exporter
spec:
  template:
    metadata:
      labels:
        k8s-app: node-exporter
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter
        env:
          - name: TZ
            value: PST8PDT
        ports:
        - containerPort: 9100
          protocol: TCP
          name: http
        volumeMounts:
        - name: date
          mountPath: "/etc/localtime"
      volumes:
      - name: date
        hostPath:
          path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: kube-prometheus
spec:
  ports:
  - name: http
    port: 9100
    targetPort: 9100
    protocol: TCP
    #  type: NodePort
  selector:
    k8s-app: node-exporter
