apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pgmon-alertmanager
  namespace: pgmon
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: "prom/alertmanager:v0.20.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --config.file=/etc/config/alertmanager.yml
            - --storage.path=/data
          ports:
            - containerPort: 9093
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9093
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: k8s-pgmon-alertmanager-config
              mountPath: /etc/config
            - name: storage-volume
              mountPath: "/data"
              subPath: ""
            - name: timezone
              mountPath: /etc/localtime
          resources:
            limits:
              cpu: 10m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
        - name: prometheus-alertmanager-configmap-reload
          image: "jimmidyson/configmap-reload:v0.3.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://localhost:9093/-/reload
          volumeMounts:
            - name: k8s-pgmon-alertmanager-config
              mountPath: /etc/config
              readOnly: true
          resources:
            limits:
              cpu: 10m
              memory: 10Mi
            requests:
              cpu: 10m
              memory: 10Mi
      volumes:
        - emptyDir: {}
          name: storage-volume
        - name: k8s-pgmon-alertmanager-config
          configMap:
            name: k8s-pgmon-alertmanager-config-email
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
