apiVersion: v1
kind: Service
metadata:
  name: k8s-pgmon-alertmanager
  namespace: pgmon
  labels:
    app: alertmanager
spec:
  type: NodePort
  ports:
  - port: 9093
    protocol: TCP
    targetPort: 9093
    nodePort: 30004
  selector:
    app: alertmanager
