apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-pgmon-alertmanager-config-email
  namespace: pgmon
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_from: CDN-Transcode-Sample@k8s.Prometheus
      smtp_smarthost: smtp.intel.com:25
      smtp_require_tls: false
      smtp_hello: outlook.com
    route:
      group_by: [linux]
      group_wait: 5s
      group_interval: 5s
      repeat_interval: 5m
      receiver: email
    receivers:
    - name: email
      email_configs:
      - to: xxxxxx@yyyyyy.com
        send_resolved: true
    inhibit_rules:
    - source_match:
        severity: critical
      target_match:
        severity: warning
      equal: [alertname, dev, instance]
